# Generated by Django 4.2 on 2023-04-20 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receipts", "0002_receiptform_delete_receipt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReceiptForm",
            new_name="Receipt",
        ),
    ]
